set(CMAKE_SYSTEM_NAME Linux)
set(TOOLCHAIN_TYPE arm_v8)
set(CMAKE_CXX_COMPILER /opt/ulaq_share/arm_v8_2021_1/compiler/aarch64-linux/bin/aarch64-linux-gnu-g++)
set(CMAKE_C_COMPILER /opt/ulaq_share/arm_v8_2021_1/compiler/aarch64-linux/bin/aarch64-linux-gnu-gcc)
set(CMAKE_SYSTEM_PROCESSOR armv8l)

set(CMAKE_SYSROOT /opt/ulaq_share/arm_v8_2021_1/filesystem/rootfs)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
